name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: build_release
    runs-on: windows-latest
    strategy:
      matrix:
        device:
          - equuleus
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Extract certificate
        shell: pwsh
        env:
          CERTIFICATE: ${{ secrets.CERTIFICATE }}
        run: Set-Content -Path ..\drivers.pfx -Value ([Convert]::FromBase64String($env:CERTIFICATE)) -AsByteStream
      - name: Package device ${{ matrix.device }}
        shell: pwsh
        env:
          PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
        run: .\extract.ps1 -CodeName ${{ matrix.device }} -Certificate ..\drivers.pfx -Password $env:PASSWORD
      - name: Create ZIP package
        shell: pwsh
        run: Compress-Archive -Path ".\output\*" -DestinationPath ${{ matrix.device }}.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.device }}.zip
